### PR TITLE
Upgrade to Asterisk 18.4.0

### PR DESCRIPTION
**Pull request by pc-m**
asterisk-rc is in version `~wazo1` this PR is in `~wazo2` to avoid having to rebase when it's time to merge.

Load tests started on 2021-05-11 13:23:00+0

### CODE REVIEW

**Comment by fblackburn1** [comment]
load tests are really weird on simultaneous calls and file descriptors used

**Comment by pc-m** [comment]
> load tests are really weird on simultaneous calls and file descriptors used

You're right, I had a configuration problem when I started the tests and the answering sipp were not running.

Tests restarted on 2021-05-12 14:15:00 +0

**Comment by bloom1** [comment]
> > load tests are really weird on simultaneous calls and file descriptors used
> 
> You're right, I had a configuration problem when I started the tests and the answering sipp were not running.
> 
> Tests restarted on 2021-05-12 14:15:00 +0

Seems like there was an issue with the tests restarting, the graphs show now calls since the restart

**Comment by pc-m** [comment]
> > > load tests are really weird on simultaneous calls and file descriptors used
> > 
> > 
> > You're right, I had a configuration problem when I started the tests and the answering sipp were not running.
> > Tests restarted on 2021-05-12 14:15:00 +0
> 
> Seems like there was an issue with the tests restarting, the graphs show no calls since the restart

:hankey: I tried this yesterday, I guess it didn't work.
```
ssh root@trafgen
rm /var/lib/munin/htmlconf.storable /var/lib/munin/limits.storable
```

I'll need to investigate some more

**Comment by pc-m** [comment]
> > > > load tests are really weird on simultaneous calls and file descriptors used
> > > 
> > > 
> > > You're right, I had a configuration problem when I started the tests and the answering sipp were not running.
> > > Tests restarted on 2021-05-12 14:15:00 +0
> > 
> > 
> > Seems like there was an issue with the tests restarting, the graphs show no calls since the restart
> 
>  I tried this yesterday, I guess it didn't work.
> 
> ```
> ssh root@trafgen
> rm /var/lib/munin/htmlconf.storable /var/lib/munin/limits.storable
> ```
> 
> I'll need to investigate some more
Fixed now

**Review by fblackburn1 — APPROVED** [review]

**Pull request merged**
