### PR TITLE
upgrade to Asterisk-16.7.0

### PR DESCRIPTION
**Pull request by pc-m**

### CODE REVIEW

**Comment by pc-m** [comment]
the `~wazo1` version is on asterisk-rc

**Comment by pc-m** [comment]
Load tests started on 2019-12-24 16:00:00+0

**Comment by fblackburn1** [comment]
Can you create a JIRA ticket related to this upgrade

**Comment by fblackburn1** [comment]
https://wazo-dev.atlassian.net/browse/WAZO-1451

**Pull request merged**
