### PR TITLE
add french core sounds

### PR DESCRIPTION
**Pull request by pc-m**

### CODE REVIEW

**Comment by pc-m** [comment]
The sound package from this build can be downloaded here https://zuul.wazo.community/logs/36/36/d35fef425414b2f1e9341a86468edcbfc568235a/check/debian-packaging/57c2f59/debian/asterisk-sounds-main_16.7.0-1~wazo7_all.deb

**Comment by pc-m** [comment]
recheck

**Comment by fblackburn1** [comment]
I don't know how it works, but shouldn't this modification be better suited to the ansible playbook? 
Like installing with variable `FR=True` will download fr sounds.
Or it must be at the compile time?

**Comment by pc-m** [comment]
> I don't know how it works, but shouldn't this modification be better suited to the ansible playbook?
> Like installing with variable `FR=True` will download fr sounds.
> Or it must be at the compile time?

I would prefer different packages for those sound files but sound files are being pulled during the Asterisk build and I don't feel the time investment to separate the core sounds from asterisk is worth it at this time.

**Pull request merged**
