### PR TITLE
WAZO-1631: increase asterisk process priority

### PR DESCRIPTION
**Pull request by sduthil**
Why:

* Asterisk is a realtime application and has priority over other
processes. We don't want to experience a loss of voice quality because
another process is occupying all the CPU cycles.

### CODE REVIEW

**Comment by pc-m** [comment]
Should I see `Nice=-19` somewhere? :confused:

**Comment by fblackburn1** [comment]
> Should I see `Nice=-19` somewhere? confused

it's the `-p` option

**Comment by pc-m** [comment]
> > Should I see `Nice=-19` somewhere? confused
> 
> it's the `-p` option

Does it have the same effect as a -19 niceness? my htop still displays a nicenes of 20

**Comment by fblackburn1** [comment]
> > > Should I see `Nice=-19` somewhere? confused
> > 
> > 
> > it's the `-p` option
> 
> Does it have the same effect as a -19 niceness? my htop still displays a nicenes of 20

Woups :laughing: well see. the -p can only be use if the process run as root
> -p     If supported by the operating system (and executing as root)


If we use user, we need to use systemd option `Nice=-19`

**Comment by sduthil** [comment]
> > > > Should I see `Nice=-19` somewhere? confused
> > > 
> > > 
> > > it's the `-p` option
> > 
> > 
> > Does it have the same effect as a -19 niceness? my htop still displays a nicenes of 20
> 
> Woups laughing .. well done. the `-p` can only be used if the process run as root
> 
> > -p     If supported by the operating system (and executing as root)
> 
> If we use a user, we need to use systemd option `Nice=-19`

I had the same reflection, but I read that the init file also used `-p` AND `-U asterisk` together, so I thought it would work, but I did not test it until now. I see the same behavior as Pascal describes, i.e. no real priority is applied to the Asterisk process when started with systemd.

After digging a bit, it seems that it's more complicated than that:
* `-p` does not seem to alter the niceness, even when run manually. In [the Asterisk code](https://github.com/asterisk/asterisk/blob/ca3c22c5f1fd042a3d42a2f421d37541e4efd47a/main/asterisk.c#L1805), it seems to trigger a call to `sched_setscheduler` which is probably blocked by `systemd` [1](https://www.freedesktop.org/wiki/Software/systemd/MyServiceCantGetRealtime/) [2](https://stackoverflow.com/questions/34018956/sched-setscheduler-error-eperm-after-installing-libpam-systemd). But it does not alter the niceness.
* When running Asterisk manually, I can see that the priority of the process is `-11` (with or without `-p`), but the niceness is always `0`

**Comment by sduthil** [comment]
I have updated the PR to start Asterisk as root, then drop the privileges. This allows running Asterisk in realtime priority (-11).

**Comment by sduthil** [comment]
regate

**Pull request merged**
