### PR TITLE
Bullseye zuul update

### PR DESCRIPTION
**Pull request by DrPyser**
https://wazo-dev.atlassian.net/browse/WAZO-3254

### CODE REVIEW

**Comment by DrPyser** [comment]
recheck

**Comment by DrPyser** [comment]
> Build failed.
> 
> * [debian-packaging-bullseye ](https://zuul.wazo.community/zuul/t/local/build/0c249e5af3cd41d387c8f843ff939cd5) : FAILURE in 6m 24s
> * [asterisk-tox-integration ](https://zuul.wazo.community/zuul/t/local/build/453c6c5b733744c9b19087e0d949a21f) : SUCCESS in 2m 38s

```
asterisk-dbgsym_20.2.1-1~wazo6_amd64.deb not greater than repository version (8:20.2.1-1~wazo6.deb11)
```

**Comment by DrPyser** [comment]
@fblackburn1 do you have intuition about what could be happening here?

**Comment by fblackburn1** [comment]
Yes [`quilt`](https://github.com/wazo-platform/asterisk/blob/master/debian/source/format) debian packaging need have their [version bumped](https://github.com/wazo-platform/asterisk/blob/master/debian/changelog) manually for each change (branch)
**But** zuul.yaml is excluded from the Jenkins config [job](https://jenkins.wazo.community/job/asterisk/).
So this PR can be merged even if `debian-packaging-bullseye` fail

**Pull request merged**
